before_install:
  - pip install jieba3k coveralls nltk
  - python -m nltk.downloader -d ~/nltk_data punkt


language: python
python:
  - "3.6"

cache:
  pip: true

install: "python setup.py develop"

script: 
  - "export DASHBOARD_CONFIG=./dashboard_test.cfg"
  - "./run_tests.sh"
  - "export DASHBOARD_LOG_DIR=./"
  - "python -m flask_monitoringdashboard.collect_performance --test_folder ./tests_zeeguu_api/ --url https://zeeguu.unibe.ch/api/dashboard"

