version: "3.8"

services:
  dev_server:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    ports:
      - 9001:9001
    volumes:
      - .:/Zeeguu-API
      - /tmp:/zeeguu-data
    entrypoint: "python /Zeeguu-API/dev.py"

  dev_play:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    volumes:
      - .:/Zeeguu-API
      - /tmp:/zeeguu-data
    entrypoint: "python tools/_playground.py"

  dev_test:
    image: zeeguu_api_dev
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/default_docker.cfg

    volumes:
      - .:/Zeeguu-API
      - /tmp:/zeeguu-data
    entrypoint: "./run_tests.sh"
